// Animation generated by Gemini
import type { ReactNode } from 'react';

type UnderwaterTextProps = {
    children: ReactNode;
};

export default function UnderwaterText({ children }: UnderwaterTextProps) {
    return (
        <>
            <svg style={{ position: 'absolute', width: 0, height: 0 }}>
                <filter id="turbulence" color-interpolation-filters="sRGB">
                    <feTurbulence
                        numOctaves="2"
                        seed="2"
                        baseFrequency="0.02 0.04"
                        result="turbulence"
                    >
                        <animate
                            attributeName="baseFrequency"
                            dur="8s"
                            values="0.02 0.04;0.03 0.05;0.02 0.04"
                            repeatCount="indefinite"
                        />
                    </feTurbulence>
                    <feGaussianBlur stdDeviation="1" in="turbulence" result="blur" />
                    <feDisplacementMap
                        scale="6"
                        in="SourceGraphic"
                        in2="blur"
                    />
                </filter>
            </svg>

            <h1 className="text-5xl md:text-9xl font-bold text-white filter-[url(#turbulence)] will-change-[filter]">
                {children}
            </h1>
        </>
    );
}